name: Build Action Sample
on: [push]
jobs:
        build-action-sample:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout the repository code
                          uses: actions/checkout@v3
                        - name: Setup jdk 17
                          uses: actions/setup-java@v3
                          with:
                                  java-version: '17'
                                  distribution: 'adopt'
                        - name: Build with Maven 3
                          run: mvn clean install
